### ISSUE TITLE
Request headers are not transmitted across redirections

### ISSUE THREAD

**Issue by sgrellet** [BRGM/gml_application_schema_toolbox#127]
# Environment

- Plugin version: 1.3.0
- QGIS version:  3.16.2-Hannover Hannover, f1660f9da5 
- Operating System: Windows 10
- Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
 
# Description

-  XML Mode - local test scenario>  3. Dereferencing vocabulary > Resolve external > Embedded
- "The external resource is not a well formed XML"
- Worked fine on plugin V 1.2.1-beta1

## To Reproduce

Follow https://brgm.github.io/gml_application_schema_toolbox/testing/scenario_mode_xml_local.html 
Do step 3 on the exact same attribut (gsmlp:purpose/@xlink:href)

## Expected behavior
Vocabulary content fetched for the URI should enrich the feature description as described in the test scenario

# Additional context

- worked under V 1.2.1-beta1: same environment
- Network Logger shows a HTTP 302 redirect from the URI (is it properly handled ?)
- is the payload retrieved logged somewhere ?

**Comment by Guts** [comment]
>     * Network Logger shows a HTTP 302 redirect from the URI (is it properly handled ?)

Yes. This is a redirection from HTTP to HTTPS:

![image](https://user-images.githubusercontent.com/1596222/110251099-2a2b7f80-7f7f-11eb-98d1-e0fab6bf304b.png)

**Comment by Guts** [comment]
>  is the payload retrieved logged somewhere ?

It was not. It's now done using the new log management. Reproducing the error:

```log
Error occurred reading the XML downloaded from http://inspire.ec.europa.eu/codelist/BoreholePurposeValue/hydrogeologicalSurvey. Trace: mismatched tag: line 88, column 2
```

**Comment by sgrellet** [comment]
Works fine now with, plugin version: 1.3.1
