### ISSUE TITLE
V 1.3.0 - GMLAS Mode - Creating SQL file - argument 1 has unexpected type 'WindowsPath' 

### ISSUE THREAD

**Issue by sgrellet** [BRGM/gml_application_schema_toolbox#128]
# Environment

- Plugin version: 1.3.0
- QGIS version:  3.16.2-Hannover Hannover, f1660f9da5 
- Operating System: Windows 10
- Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 

# Description

- Relational mode (GMLAS) scenario - Local test scenario > step "1. initial information seed"
- following the steps
> TypeError: setText(self, str): argument 1 has unexpected type 'WindowsPath' 

## To Reproduce

Follow https://brgm.github.io/gml_application_schema_toolbox/testing/scenario_mode_gmlas_local.html
Do step 1 as described

- all default options EXCEPT
- “Load layer list’ : click and keep both ‘boreholeview’ and ‘boreholeview_name’
- Target database > SQLite (write mode : Create)
- click on "Finish"
> Python error

## Expected behavior

- as described in the test scenario > "_Expected result : 1 new QGIS layer (boreholeview) and 1 table_"
And SQLite file create where specified

# Additional context

- worked under V 1.2.1-beta1 : same environment

## Logs

```logs
TypeError: setText(self, str): argument 1 has unexpected type 'WindowsPath' 
Traceback (most recent call last):
  File "C:/Users/grellets/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gml_application_schema_toolbox\gui\database_widget.py", line 104, in on_sqlitePathButton_clicked
    self.sqlitePathLineEdit.setText(filepath)
TypeError: setText(self, str): argument 1 has unexpected type 'WindowsPath'
```

**Comment by sgrellet** [comment]
Works fine now with plugin version: 1.3.1

**Comment by Guts** [comment]
related to #130
