### ISSUE TITLE
Error messages

### ISSUE THREAD

**Issue by mhugo** [BRGM/gml_application_schema_toolbox#22]
Using plugin 1.1.0.zip
Importing the following URI (http://ressource.brgm-rec.fr/data/Piezometre/06512X0037/STREMY.2) using GMLAS triggers
1°/ this stack trace
note that contrary to the message '20170711_EF.sqlite' is created and
RuntimeError: SQLite driver failed to create D:/Temp/20170711_EF.sqlite and all the tables appear in the QGIs project
Traceback (most recent call last):
File "C:/Users/grellets/.qgis3/python/plugins\gml_application_schema_toolbox\gui\import_gmlas_panel.py", line 280, in on_convertButton_clicked
self.translate(self.import_params())
File "C:/Users/grellets/.qgis3/python/plugins\gml_application_schema_toolbox\gui\gmlas_panel_mixin.py", line 65, in translate
res = gdal.VectorTranslate(**params)
File "C:\OSGEO41\apps\Python36\lib\site-packages\osgeo\gdal.py", line 718, in VectorTranslate
return wrapper_GDALVectorTranslateDestName(destNameOrDestDS, srcDS, opts, callback, callback_data)
File "C:\OSGEO41\apps\Python36\lib\site-packages\osgeo\gdal.py", line 3025, in wrapper_GDALVectorTranslateDestName
return _gdal.wrapper_GDALVectorTranslateDestName(*args)
RuntimeError: SQLite driver failed to create D:/Temp/20170711_EF.sqlite

2°/ this error message when clicking on the point created using 'identify'
'Access violation - no RTTI data !'

I don't know if 100% related but part of the behaviour is the same
Importing that URI (https://forge.brgm.fr/svnrepository/epos/trunk/instances/BoreholeView.xml) in GMLAS triggers the stack trace below eventhough the sqlite file is created and the project loaded in the GUI (but I can't do nothing with the content).

Stack trace :
File "C:/Users/grellets/.qgis3/python/plugins\gml_application_schema_toolbox\gui\import_gmlas_panel.py", line 288, in on_convertButton_clicked
'postgres' if self.databaseWidget.format() == 'PostgreSQL' else 'spatialite')
File "C:/Users/grellets/.qgis3/python/plugins\gml_application_schema_toolbox\core\load_gmlas_in_qgis.py", line 79, in import_in_qgis
raise RuntimeError("SQL error")
RuntimeError: SQL error

**Comment by mhugo** [comment]
@sgrellet the import logic has been changed. Could you retest with the last version ?
https://github.com/BRGM/gml_application_schema_toolbox/releases/download/v1.1.1/gml_application_schema_toolbox-1.1.1.zip

**Comment by sgrellet** [comment]
'Load layer and configure' seems better. I can interrogate the created feature
-> maybe rename it into 'convert and load' (to be consistent with the other one)

But when interogating a feature I have
- encoding issues (ex : on the <ef:name>Piézomètre de St-Rémy - 01</ef:name> -> PiÃ©zomÃ¨tre de St-RÃ©my - 01)
- and also several 'Missing Relation in configuration' appearing in the General log tab when trying to change the information displayed in form mode (for example for xxx_belongsTo association (where 'http://ressource.brgm-rec.fr/data/Piezometre/06512X0037/STREMY.2' proposed 7 different ones)

**Comment by mhugo** [comment]
> -> maybe rename it into 'convert and load' (to be consistent with the other one)
Well actually, there are really two operations: convert to db and then load layers from an existing db.
Splitting in two operations allows to reopen a project from an existing db

I'll have a look for the two other issues

**Comment by sgrellet** [comment]
so the proposed new name fits perfectly :)

**Comment by mhugo** [comment]
> and also several 'Missing Relation in configuration' appearing in the General log tab when trying to change the information displayed in form mode (for example for xxx_belongsTo association (where 'http://ressource.brgm-rec.fr/data/Piezometre/06512X0037/STREMY.2' proposed 7 different ones)

I can't reproduce. I have all the "belongsTo" links populated and working corrrectly. What do you mean by "when trying to change the information displayed in form mode" ?

**Comment by mhugo** [comment]
> encoding issues

Fixed in https://github.com/BRGM/gml_application_schema_toolbox/commit/f14210026661052b9b6fdfbc5d3fad57e4a73102
