### ISSUE TITLE
Change Help documentation link 

### ISSUE THREAD

**Issue by sgrellet** [BRGM/gml_application_schema_toolbox#23]
In the plugin the link behind 'Check the plugin documentation to learn how to use it'. should point to 'https://github.com/BRGM/gml_application_schema_toolbox/blob/master/README.md' instead

**Comment by mhugo** [comment]
Fixed in https://github.com/BRGM/gml_application_schema_toolbox/commit/587de7e7b06536823cd6b7d4e10efa49ea2029f5
