### ISSUE TITLE
"Download tab" does not work

### ISSUE THREAD

**Issue by mhugo** [BRGM/gml_application_schema_toolbox#27]
Trying to download gmlp:BoreholeView from http://resource.europe-geology.eu/service/wfsBorehole results in this error message: "Feature type :g unknown"

**Comment by mhugo** [comment]
Fixed

**Comment by sgrellet** [comment]
Tested using 1.1.5 on 
- https://wfspoc.brgm-rec.fr/geoserver/ows?
- and http://resource.europe-geology.eu/service/wfsBorehole?
generates the attached error
![wfsborehole](https://user-images.githubusercontent.com/16756304/32504936-48380fc8-c3e1-11e7-9e5e-a44a918cd584.png)
![geoserver_ows](https://user-images.githubusercontent.com/16756304/32504937-4851d20a-c3e1-11e7-91ad-a5acb54d5ca9.png)

**Comment by mhugo** [comment]
I've reverted changes introduced in 85596a4313473eacda039f64b2167d7b7b5e6f1c 
Download now works with WFS 2.0.
Stored queries are listed
