### ISSUE TITLE
XML mode GUI issue : handling complex GML geometry ?

### ISSUE THREAD

**Issue by sgrellet** [BRGM/gml_application_schema_toolbox#30]
When loading the following URI (http://ressource.brgm-rec.fr/data/EntiteHydroGeol/121AT30) the feature is correctly identified but it is not possible to retrieve information from it with the 'identify' function.

As this resource is related to another issue #29, I removed manually the un-necessary FeatureCollection / Members.
See file attached (remove the trailing .txt for import): 
[EntiteHydroGeol.121AT30.xml.txt](https://github.com/BRGM/gml_application_schema_toolbox/files/1214187/EntiteHydroGeol.121AT30.xml.txt)
But the problem remains.

Is it linked to the complex geometry that may cause issue to store it temporarily in SpatialLite ?

**Comment by mhugo** [comment]
This seems to be related to a particular geometry invalidity case that QGIS has problems to handle correctly ...

**Comment by mhugo** [comment]
When exporting the geometry in PostGIS:
<pre>
select st_isvalid(geom) from ta;
NOTICE:  Hole lies outside shell at or near point 1.6533408259337787 50.621265734925082
</pre>

**Comment by mhugo** [comment]
Works correctly in GMLAS mode.
The XML mode is using the OGR Python API to extract the geometry from XML though

**Comment by mhugo** [comment]
@sgrellet using the equivalent of ST_MakeValid() in QGIS seems to solve the problem.
Do you think we need a checkbox "[ ] Make geometries valid" ?

**Comment by sgrellet** [comment]
@mhugo : I received so many comments regarding the client saying : "that's cool but not accessible to the layman" that I would force it implicitly. Is there a way to log somewhere on the client side that initially the geom was invalid (I am afraid this will trigger another pass on the geometry no?)

**Comment by mhugo** [comment]
@sgrellet ok :) Actually, I am digging deeper, and the geometry should not be invalid here. The code is creating a polygon, where we should have a multipolygon ... investigations in progress.

**Comment by mhugo** [comment]
It was just that multipolygons was not handled. Fixed now
