### ISSUE TITLE
Convert Tab -> move import button up

### ISSUE THREAD

**Issue by sgrellet** [BRGM/gml_application_schema_toolbox#35]
Put it before the 'attribute mapping' section

**Comment by mhugo** [comment]
I've put all the options in an "Options" group that is collapsed by default. @sgrellet  What do you think ?

![capture du 2017-11-08 14-39-20](https://user-images.githubusercontent.com/1618556/32551988-b7152e38-c492-11e7-9a15-e9b244ce255b.png)
![capture du 2017-11-08 14-39-30](https://user-images.githubusercontent.com/1618556/32551995-bcc172ce-c492-11e7-880e-5c8449100cba.png)

**Comment by sgrellet** [comment]
+1

**Comment by sgrellet** [comment]
No need since the wizard (#49)
