### ISSUE TITLE
GUI : Convert Tab -> Convert, Load & Import in one action

### ISSUE THREAD

**Issue by sgrellet** [BRGM/gml_application_schema_toolbox#36]
Convert, Load & Import in one action and move the 'Load and configure layers' dans un autre onglet ou dans download

**Comment by mhugo** [comment]
Could'nt we also have a merge with the "Download" tab when the source is a URL ?

I think most users just want to "open" and "see" a GML "layer". We could have something very close to the standard "Data source manager" with some more checkboxes to specify advanced options

![capture du 2017-11-08 15-48-51](https://user-images.githubusercontent.com/1618556/32555198-67f18f22-c49c-11e7-927d-3cc5977ed6fc.png)

**Comment by mhugo** [comment]
(note: onglet ajoutable via QgsGui.sourceSelectProviderRegistry().addProvide())

**Comment by sgrellet** [comment]
> "I think most users just want to "open" and "see" a GML "layer". 
I tend to have the same feeling but, conceptually, "seeing a WFS layer" would be more via the associated WMS on the same Feature if available.

> "(note: a new tab can be added via QgsGui.sourceSelectProviderRegistry().addProvide())"
sorry, I don't get it. which interface are you referring to ? 'Data source manager' or 'GMLAS toolbox' one ?

> "Could'nt we also have a merge with the "Download" tab when the source is a URL ?"
I see an issue to that. URL does not always mean 'a URL to a WFS endpoint'. We are more and more moving in a direction where we put in the 'URL' field a URI to a resource.

-> trying to sort this out in my brain.
Shouldn't we : 
- 1: try to port the content of the 'Download' tab that is above the 'filter by extent' to the 'Data source manager'. 
- 2: then, in the convert Tab enable from the URL field to either pick a WFS defined in the 'Data source manager' or type a URL/URI by hand.
- 3: if, in the convert Tab, the user picks a WFS defined in the 'Data source manager' this triggers a dialog box with the bottom part of the current download tab (below 'filter by extent').
?

**Comment by mhugo** [comment]
> I see an issue to that. URL does not always mean 'a URL to a WFS endpoint'. We are more and more moving in a direction where we put in the 'URL' field a URI to a resource.

Good point.

Could we say a "resource" is : 
- either a layer of a WFS
- a URL
- or a path to a local file

> 1: try to port the content of the 'Download' tab that is above the 'filter by extent' to the 'Data source manager'.

I was thinking of the whole "Download" tab + the whole "Convert" tab actually. But I may be missing a use case where the user wants to download something from a WFS2 server with QGIS and do nothing else with the file. Is it a real use case ?

**Comment by mhugo** [comment]
@sgrellet I've worked a bit on a UI refactoring.

Ideas:
- reuse QGIS standard WFS connections settings
- turn all option panels into "collapsible" groups
- make the default options just "work" and let the possibility to change advanced options
- move the "export" panel to a new entry in the menu
- move the "load and configure" button to a new entry in the menu
- autodetect WFS server version

You can see a video showing the current state here:
https://share.oslandia.net/public/aeaab3

There are still 2 panels, but I think they can be merged in only one.

@sgrellet What do you think ?

**Comment by sgrellet** [comment]
+1 , I like it 
I'm also in favour of mergin the 2 panels as I wrote above 
But, you're right, there may be use cases where people just want to download from a WFS and do nothing else within the plugin afterwards 

2 questions from my side : 
? do we keep the from URL/File or no (it isn't in the parallel zip file you sent me) ? I would keep it in case people just want to collect a resource from the web and do nothing with the plugin afterwards (see above)

? can we have the plugin menu also available from the toolbox panel (ex : under a menu tab) ?

**Comment by mhugo** [comment]
Thanks.

> But, you're right, there may be use cases where people just want to download from a WFS and do nothing else within the plugin afterwards

Actually, I was asking the question because I am not sure this is a real use-case ... 

Anyway, what I can propose: I will merge the two panels and by default the user just has to choose the input source (WFS, URL or a file) and then the type of opening mode (XML or relational) and then click on "Load". I will keep the download button in case the user just wants it.

> ? can we have the plugin menu also available from the toolbox panel (ex : under a menu tab) ?

Sure, I'll see what I can do.

**Comment by mhugo** [comment]
I've merged panels 
![capture du 2018-01-15 14-28-32](https://user-images.githubusercontent.com/1618556/34944560-646ed622-fa00-11e7-9c78-44ffcc85f66a.png)

You can test it with the pre-release https://github.com/BRGM/gml_application_schema_toolbox/releases/tag/v1.2.0-rc1

**Comment by mhugo** [comment]
Superseded by #49
