### ISSUE TITLE
Custom widgets in GMLAS driver mode

### ISSUE THREAD

**Issue by sgrellet** [BRGM/gml_application_schema_toolbox#44]
Enable the custom widgets from the forms when DB structure was generated by the GMLAS driver mode (was in the first ProofOfConcept).
Enable them also from the Database Model Viewer widget

**Comment by mhugo** [comment]
Done, testable in the prelease 1.2.0. Custom viewers are in a new "Custom viewers" tab
https://github.com/BRGM/gml_application_schema_toolbox/releases/tag/v1.2.0-rc1

![capture du 2018-01-15 14-30-04](https://user-images.githubusercontent.com/1618556/34944615-a0fa671e-fa00-11e7-8648-929f15b2fdb7.png)

**Comment by sgrellet** [comment]
linked to #50

**Comment by sgrellet** [comment]
Time series ok. Need to be tested on BoreholeLog

**Comment by sgrellet** [comment]
on GMLAS toolbox plugin : v1.2.0-rc6
- ok for WaterML2 timeseries
- ko for BoreholeLog according to GWML2 Log : seems the result structure is not considered by GMLAS driver (OGC SWE soft typing see https://github.com/BRGM/gml_application_schema_toolbox/blob/master/samples/swe/GW_GeologyLog/BSS001REWW_Log.xml). Will open a specific issue on this.

Python : 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)]
QGIS : 3.0.1-Girona Girona, a86bec25ebw

**Comment by sgrellet** [comment]
No further dev on this as the community is moving to providing Log Data (still compliant to GWML2) but using newer OGC APIs (Features &| SensorThings API)
