### ISSUE TITLE
WFS1 support

### ISSUE THREAD

**Issue by mhugo** [BRGM/gml_application_schema_toolbox#45]
The "download" tab does not work with 1.x servers

(for instance https://api.kuntatietopalvelu.fi/demo/wfs?service=wfs )

**Comment by mhugo** [comment]
Fixed in https://github.com/BRGM/gml_application_schema_toolbox/commit/f89be8f99d6b6286fedc03a1db8d830f027021a2

**Comment by sgrellet** [comment]
tested ok for the XML mode on : http://services.sandre.eaufrance.fr/geo/eth_FXX? (Mapserver based)
have an issue with opening on Relational model (GMLAS) but seems a server side not toolbox issue

Using
Python : 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)]
QGIS : 3.0.0-Girona Girona, 001c80b0c3
GMLAS toolbox plugin v1.2.0-rc2
