### ISSUE TITLE
Please add a more informative home page

### ISSUE THREAD

**Issue by pcav** [BRGM/gml_application_schema_toolbox#5]
Not a generic one.
Thanks.

**Comment by mhugo** [comment]
Hi @pcav 
Is the source + README.md page of github ok ?
https://github.com/Oslandia/gml_application_schema_toolbox

**Comment by pcav** [comment]
Yes

**Comment by mhugo** [comment]
Should be fixed now, thanks

**Comment by vpicavet** [comment]
Would be great to have some background info on Complex Feature and INSPIRE on the page
