### ISSUE TITLE
Add cutsomviewer icons in legend

### ISSUE THREAD

**Issue by mhugo** [BRGM/gml_application_schema_toolbox#50]
GMLAS mode: add customviewer icon in the legend, next to the layer icon

**Comment by mhugo** [comment]
Example

![capture du 2018-01-22 16-12-32](https://user-images.githubusercontent.com/1618556/35227767-3c889154-ff8f-11e7-8325-c433391140f8.png)

**Comment by sgrellet** [comment]
thanks. apparently I cannot action anything the widget when clicking on it. Haven't tried on BoreholeLog yet. Is that on purpose ?
