### ISSUE TITLE
"About": add former dev / funders

### ISSUE THREAD

**Issue by mhugo** [BRGM/gml_application_schema_toolbox#55]

**Comment by sgrellet** [comment]
Funder : European Environment Agency (Copernicus funding), GiPO ?
Dev: CampToCamp, Spatialys
other ?

**Comment by mhugo** [comment]
![capture du 2018-04-12 15-15-09](https://user-images.githubusercontent.com/1618556/38679536-4fe078f2-3e64-11e8-915f-8e74954e43a3.png)
