### ISSUE TITLE
WFS 'filter - use layer/canvas extent' ko

### ISSUE THREAD

**Issue by sgrellet** [BRGM/gml_application_schema_toolbox#57]
Connected to https://wfspoc.brgm-rec.fr/geoserver/ows 
Just having a WMS layer as a background
'use layer/canvas extent' returns the following stack trace

AttributeError: module 'processing.tools.dataobjects' has no attribute 'getAllLayers' 
Traceback (most recent call last):
  File "C:/Users/grellets/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gml_application_schema_toolbox\gui\bbox_widget.py", line 67, in useLayerExtent
    layers = dataobjects.getAllLayers()
AttributeError: module 'processing.tools.dataobjects' has no attribute 'getAllLayers'

Version de Python : 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)] 
Version de QGIS : 2.99.0-Master Master, b4be39f98b

**Comment by sgrellet** [comment]
The layer chooser pop-ups properly but it seems we have a pb.
In the GUI the text says 'x min, y min, x max, ymax, ...' but it seems it is filled with X min, X Max, Y min, Y Max (same as when you 'select extent on canvas')
Moreover "-180.0,180.0,-90.0,90.0,EPSG:4326 " is taken from a worldwide WMS backdrop but the WFS query is https://wfspoc.brgm-rec.fr:443/geoserver/wfs?service=WFS&version=2.0.0&request=GetFeature&bbox=90.0,-180.0,180.0,-90.0,urn:ogc:def:crs:EPSG::4326&typenames=ef:EnvironmentalMonitoringFacility

wheras it should be (minX, min Y, max x, max Y) https://wfspoc.brgm-rec.fr:443/geoserver/wfs?service=WFS&version=2.0.0&request=GetFeature&bbox=-180,-90,180,90,urn:ogc:def:crs:EPSG::4326&typenames=ef:EnvironmentalMonitoringFacility

**Comment by mhugo** [comment]
Orders of the parameters depend on the projection

**Comment by mhugo** [comment]
Ok, got it. The last commit https://github.com/BRGM/gml_application_schema_toolbox/commit/4060d9dc95c3878f1893998ae6ec06f87d83e840 should fix the problem

**Comment by sgrellet** [comment]
not tested under v.1.2.0-rc3 because of #53

**Comment by sgrellet** [comment]
fixed under
GMLAS toolbox plugin : v1.2.0-rc4
Python : 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)]
QGIS : 3.0.1-Girona Girona, a86bec25ebw
