### ISSUE TITLE
WFS autodetect generates wrong WFS getCap query

### ISSUE THREAD

**Issue by sgrellet** [BRGM/gml_application_schema_toolbox#62]
Setting WFS version on 'auto-detect' when defining a WFS endpoint generates the following request
http://services.sandre.eaufrance.fr/geo/eth_FXX&request=GetCapabilities&acceptversions=2.0.0,1.1.0,1.0.0
whereas it should be 
http://services.sandre.eaufrance.fr/geo/eth_FXX?service=wfs&request=GetCapabilities&acceptversions=2.0.0,1.1.0,1.0.0
the '?' was not added and service=WFS is missing

Version de Python : 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)] 
Version de QGIS : 3.0.0-Girona Girona, 001c80b0c3 
GMLAS toolbox v1.2.0-rc2

**Comment by mhugo** [comment]
Fixed with https://github.com/BRGM/gml_application_schema_toolbox/commit/7f6061a542290e0acf4715fa752a7cc02643622c

**Comment by sgrellet** [comment]
fixed under GMLAS toolbox plugin : v1.2.0-rc5
Python : 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)]
QGIS : 3.0.1-Girona Girona, a86bec25ebw
