### ISSUE TITLE
can't edit the target database

### ISSUE THREAD

**Issue by tschuettenberg** [BRGM/gml_application_schema_toolbox#63]
Hi! Testing the nice UI refactoring in 1.2.0-rc3 I came across that I can't switch the target database (PostgreSQL) under Relational mode (GMLAS) anymore(?), although there are several postgis-connections stored in the QGIS data source manager. 

The database dropdown list does not show them and the ...-button does not work. Is it broken or do I miss something?
Cheers!

**Comment by mhugo** [comment]
Hi @tschuettenberg. Thanks for your feedback. I'll touch a bit the UI again in the coming weeks. I hope this will fix these kinds of issues. Stay tuned ! :)

**Comment by mhugo** [comment]
@tschuettenberg Do you still have the problem with -rc4 or -rc5 ? https://github.com/BRGM/gml_application_schema_toolbox/releases

**Comment by Guts** [comment]
Hi @tschuettenberg .

I know it was a long time ago but could you confirm that the mentioned UI issue is now fixed?

Because this issue could be considered as staled, I close it but it'll still be possible to repoen it if needed.

**Comment by tschuettenberg** [comment]
Hi @Guts ,
sorry for not responding back then.
You did right and I can confirm that the UI issue is fixed in v1.2.0
Thank you!
