### ISSUE TITLE
1.2.0 rc3 : installed with success on Mac but not visible

### ISSUE THREAD

**Issue by sgrellet** [BRGM/gml_application_schema_toolbox#64]
under macOS Sierra (version 10.12), italian
QGIS 3.0.0-Girona in italian

Zip install of 1.2.0 rc3 is written successful and the plugin files are under ...python/plugins/gml_application_schema_toolbox

But no GMLAS ToolBox panel appear and it is not proposed under 'Visuealizza/Pannelli/...' and neither in 'Plugins' menu. Whereas other plugins are correctly proposed (test on OSM plugin).

Mac or internationalisation issue ?

**Comment by mhugo** [comment]
Did you tick the plugin in the plugin manager ?

**Comment by sgrellet** [comment]
I contacted Carlo, here is the reply
"Yes I try to tick the plugin, but when I click obtain this error: Impossibile caricare il plugin 'gml_application_schema_toolbox' a causa di un errore chiamando il metodo classFactory() 
Regards,
Carlo"

**Comment by sgrellet** [comment]
Issue cleaning. Closed
