### ISSUE TITLE
Allow to set a custom User Agent

### ISSUE THREAD

**Issue by mhugo** [BRGM/gml_application_schema_toolbox#67]
Allow the plugin to use a custom User Agent when making HTTP requests.

Things that need to be set:
- when using gdal.OpenEx('/vsicurl...'), setting GDAL_HTTP_USER_AGENT https://trac.osgeo.org/gdal/wiki/ConfigOptions#GDAL_HTTP_USERAGENT
- with urllib2, use addheaders https://stackoverflow.com/questions/802134/changing-user-agent-on-urllib2-urlopen
- for owslib: not designed for, no simple solution

**Comment by mhugo** [comment]
User-Agent set for gdal and qgis / urllib

**Comment by sgrellet** [comment]
Great. Which tag/string did you use ? (to anticipate our resolver configuration)

**Comment by mhugo** [comment]
![capture d ecran de 2018-05-30 15-15-16](https://user-images.githubusercontent.com/1618556/40723320-f8d04df4-641e-11e8-87bd-1e6c53ed9385.png)

It's configurable in the settings

**Comment by sgrellet** [comment]
Nice

**Comment by sgrellet** [comment]
using v1.2.0-rc7
Version de Python : 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)]
Version de QGIS : 3.0.1-Girona Girona, a86bec25eb

Opening plugin settings, not touching anything an pressing 'OK'.

NameError: name 'httpUserAgentEdit' is not defined
Traceback (most recent call last):
  File "C:/Users/grellets/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gml_application_schema_toolbox\gui\settings_dialog.py", line 103, in accept
    self.save_settings()
  File "C:/Users/grellets/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gml_application_schema_toolbox\gui\settings_dialog.py", line 44, in save_settings
    settings.setValue('http_user_agent', self.http_user_agent())
  File "C:/Users/grellets/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gml_application_schema_toolbox\gui\settings_dialog.py", line 59, in http_user_agent
    return httpUserAgentEdit.text()
NameError: name 'httpUserAgentEdit' is not defined

**Comment by sgrellet** [comment]
note : the User-Agent value is passed properly as it is logged by our resolver

**Comment by mhugo** [comment]
Fixed

**Comment by sgrellet** [comment]
ok under
GMLAS toolbox plugin : v1.2.0
Version de Python : 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)]
Version de QGIS : 3.0.1-Girona Girona, a86bec25eb
