### ISSUE TITLE
mismatch on coordinates when data are projected

### ISSUE THREAD

**Issue by mbeaufils** [BRGM/gml_application_schema_toolbox#7]
When trying to display items provided by the plugin over a WMS layer, I found that items added with the plugin are not well projected.

This point : http://ressource.brgm-rec.fr/data/Piezometre/00634X0147/PZ1.2 now appears near Somalia as shown on the screenshot.
![screen](https://cloud.githubusercontent.com/assets/17067226/20179957/b2070b1c-a758-11e6-8b80-ccd17ff2f316.png)

I suppose projection are not well defined and then a mismatch with lon lat is done when trying to project data on the map (inversion of lon and lat).

**Comment by mhugo** [comment]
This is fixed on master.
But this is a very strange issue. I had to swap coordinates coming from an OGR geometry. I usually tend to trust OGR for that :)
Interesting reading : http://docs.geotools.org/latest/userguide/library/referencing/order.html
So I am not sure yet if this is really an error. And it seems we would need to expose an option to allow for 4326 coordinate inversion

**Comment by mhugo** [comment]
Fixed in 7ed8550
A new checkbox has been added to swap X/Y coordinates

**Comment by mhugo** [comment]
I've just added two commits that should improve the situation:
- use OGR to detect SRID that should be inverted (thanks @rouault ). Most of the time, there should be no need to touch the "Swap X/Y" checkbox
- add a "Swap X/Y" checkbox to the "Resolve external" menu (see picture)

![swap_xy_submenu](https://user-images.githubusercontent.com/1618556/32452019-aaa17fc4-c318-11e7-8077-09e78d08236d.png)

**Comment by mhugo** [comment]
FYI, QGIS has some options related to this topic in its WFS connection settings.
Two options:
- Ignore axis orientation
- Invert axis orientation

![capture du 2017-11-13 12-00-32](https://user-images.githubusercontent.com/1618556/32722532-7324c838-c86a-11e7-9ee7-d51e5986adac.png)

Maybe we could reuse these two options for consistency

**Comment by sgrellet** [comment]
+1
