### ISSUE TITLE
BoreholeLog Widget crashed

### ISSUE THREAD

**Issue by sgrellet** [BRGM/gml_application_schema_toolbox#70]
Under GMLAS toolbox plugin : v1.2.0-rc6
The same URI under rc2 works fine : http://ressource.brgm-rec.fr/obs/RawGeologicLogs/BSS001REWW

Une erreur est survenue lors de l'éxécution du code Python: 

TypeError: 'NoneType' object is not iterable 
Traceback (most recent call last):
  File "C:/Users/grellets/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gml_application_schema_toolbox\gui\xml_tree_widget.py", line 64, in show_viewer
    widget.w = custom_viewer_widget.init_from_xml(elt)
  File "C:/Users/grellets/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gml_application_schema_toolbox\viewers\geology_logs.py", line 46, in init_from_xml
    for log in logs:
TypeError: 'NoneType' object is not iterable

Python : 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)]
QGIS : 3.0.1-Girona Girona, a86bec25ebw

**Comment by mhugo** [comment]
Should be fixed (will be included in next -rc)

**Comment by sgrellet** [comment]
GMLAS toolbox plugin : v1.2.0-rc7

works fine with 
http://ressource.brgm-rec.fr/obs/RawEarthMaterialLogObservation/BSS001REWW.1596478
xPath to labels : observation/OM_Observation/result/GW_GeologyLogCoverage/element/LogValue/value/DataRecord/field/Text/value

but no label with http://ressource.brgm-rec.fr/obs/RawGeologicAgeLogObservation/BSS001REWW.1596479
different xPath to labels observation/OM_Observation/result/GW_GeologyLogCoverage/element/LogValue/value/DataRecord/field/Category/value

looking at 'viewers/geology_logs.py', it seems 
"value = value_text if value_text is not None else value_cat" does not do its job

Version de Python : 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)]
Version de QGIS : 3.0.1-Girona Girona, a86bec25eb

**Comment by sgrellet** [comment]
ok under
GMLAS toolbox plugin : v1.2.0
Version de Python : 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)]
Version de QGIS : 3.0.1-Girona Girona, a86bec25eb
