### ISSUE TITLE
Excludes can be None in proxy

### ISSUE THREAD

**Issue by ianturton** [BRGM/gml_application_schema_toolbox#85]
In core/proxy.py:

 26         excludes = settings.value("proxy/proxyExcludedUrls", "")                
 27         if hasattr(excludes, 'isNull') and excludes.isNull(): 
 28             excludes = []                                                       
 29         else:                                                                   
 30             excludes = excludes.split("|")                                     

If excludes in None then line 30 throws an exception.
fix to:

 26         excludes = settings.value("proxy/proxyExcludedUrls", "")                
 27         if not excludes or (hasattr(excludes, 'isNull') and excludes.isNull()): 
 28             excludes = []                                                       
 29         else:                                                                   
 30             excludes = excludes.split("|")                  

## Environment

QGIS version | 3.6.3-Noosa | QGIS code revision | 0c5774c
-- | -- | -- | --
Compiled against Qt | 5.9.5 | Running against Qt | 5.9.5
Compiled against GDAL/OGR | 2.2.3 | Running against GDAL/OGR | 2.2.3
Compiled against GEOS | 3.6.2-CAPI-1.10.2 | Running against GEOS | 3.6.2-CAPI-1.10.2 4d2925d6
PostgreSQL Client Version | 10.8 (Ubuntu 10.8-0ubuntu0.18.04.1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.2
PROJ.4 Version | 493

**Comment by Guts** [comment]
Anterior to the duplicated #88, but less documented.
Please follow up the new one.
