### ISSUE TITLE
Plugin does not load with QGIS 3.14+

### ISSUE THREAD

**Issue by wonder-sk** [BRGM/gml_application_schema_toolbox#90]
In QGIS 3.14 or in QGIS master the plugin fails to load:

![Screenshot from 2020-06-24 15-35-47](https://user-images.githubusercontent.com/193367/85566527-6bb60d80-b630-11ea-94a3-0d657e91f38a.png)

This is due to the fact that the plugin used a private module from Processing, which got removed in 3.14: https://github.com/qgis/QGIS/commit/4edc7d11d95875431ac9ec3d730d192e5306f108#diff-2fa32fc853cf33496bfdd34f6cb89b40

**Comment by Soph-38** [comment]
Hello, 
I have the same issue with processing.tools.postgis not found in Qgis 3.14 (under linux).
This is problematic for gml_application_schema_toolbox extension.


![snapshot_processing_tools_postgis](https://user-images.githubusercontent.com/68636173/88155222-1a397800-cc08-11ea-8a3a-e1c8d53161da.png)

**Comment by MaChriSchmi** [comment]
Hello,
there are this issue also on the version 3.10.8 LTR?

**Comment by yodaanneaux** [comment]
Same issue with 3.14.15 on Windows. Like @wonder-sk said, the reason of this bug is known and has been reported here => qgis/QGIS/issues/35213

**Comment by vpicavet** [comment]
Hi, we plan to work on updating the plugin and make it compatible with QGIS 3.10 and/or QGIS 3.16.

Please be patient. You can also help us by funding this effort, any additional funding will go to consolidation, documentation and examples.
