### ISSUE TITLE
Compatibility with QGIS >= 3.16

### ISSUE THREAD

**Issue by Guts** [BRGM/gml_application_schema_toolbox#94]
A new development cycle is started from tomorrow. The first goal is to make this plugin compatible with QGIS version 3.16. This issue is a "hub" of others related to QGIS compatibility.

## Related issues

- [x] https://github.com/BRGM/gml_application_schema_toolbox/issues/90
- [x] https://github.com/BRGM/gml_application_schema_toolbox/issues/89

**Comment by Guts** [comment]
<details>
 <summary>Spoiler alert</summary>

![image](https://user-images.githubusercontent.com/1596222/102626360-fe9ab500-4146-11eb-9a46-d7862958b779.png)

</details>

**Comment by gioman** [comment]
> Spoiler alert

@Guts tried to install your latest release on 3.16.1 on ubuntu 20.04

```
ModuleNotFoundError: No module named 'processing.tools.postgis' 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/giovanni/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gml_application_schema_toolbox/__init__.py", line 35, in classFactory
    from .main import MainPlugin
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/giovanni/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gml_application_schema_toolbox/main.py", line 33, in 
    from .gui.database_widget import DatabaseWidget
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/giovanni/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gml_application_schema_toolbox/gui/database_widget.py", line 12, in 
    from gml_application_schema_toolbox.core.gmlas_postgis_db import GmlasPostgisDB
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/giovanni/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gml_application_schema_toolbox/core/gmlas_postgis_db.py", line 3, in 
    from processing.tools.postgis import GeoDB
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'processing.tools.postgis'
```

**Comment by Guts** [comment]
> @Guts tried to install your latest release on 3.16.1 on ubuntu 20.04

@gioman when you say "latest release", you mean that you downloaded it from GitHub https://github.com/BRGM/gml_application_schema_toolbox/releases/tag/1.2.1-beta1 ?

Because I've just tested also on Windows today and it's working:

![image](https://user-images.githubusercontent.com/1596222/102711535-b4d2db80-42ba-11eb-9d2b-70973e4fbca3.png)

**Comment by gioman** [comment]
> @gioman when you say "latest release", you mean that you downloaded it from GitHub https://github.com/BRGM/gml_application_schema_toolbox/releases/tag/1.2.1-beta1 ?

@Guts 
Thanks for the quick answer. I mean the new version that just appeared in the QGIS plugins repository.

**Comment by Guts** [comment]
@gioman to be sure, did you select the "Experimental plugin" installation option?

![image](https://user-images.githubusercontent.com/1596222/102711828-c5845100-42bc-11eb-95a1-43cc24f1379e.png)




(sorry I'm on Windows today, specifically to test against this OS)

**Comment by gioman** [comment]
> (sorry I'm on Windows today, specifically to test against this OS)

@Guts sorry for the noise, for some reason from here the plugin manager only had available 1.2, now the beta is available and installs ok. Thanks!

**Comment by Guts** [comment]
No worry @gioman, I'd rather have false positives than miss something :wink: .

And this is a beat so it's still unstable so feel free to test and report or update some of issues :tickets: .

**Comment by gioman** [comment]
@Guts thanks Julien

As start I can say that I was able to import GML file like http://inspire.ine.pt/AD/atom/gml/Addresses_4801_EPSG4258.zip (a sample of address from Portugal, following the INSPIRE data model) which never worked with previous release, if I recall correctly.


While navigating trough the tables and relations at some point I got a python error
```
Traceback (most recent call last):
  File "/home/giovanni/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gml_application_schema_toolbox/gui/qgis_form_custom_widget.py", line 169, in 
    lambda checked, dlg=dialog, l=layer, f=feature, fd=field_name: on_resolve_href(
  File "/home/giovanni/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gml_application_schema_toolbox/gui/qgis_form_custom_widget.py", line 178, in on_resolve_href
    return on_resolve_href_(dialog, layer, feature, field)
  File "/home/giovanni/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gml_application_schema_toolbox/gui/qgis_form_custom_widget.py", line 216, in on_resolve_href_
    with remote_open_from_qgis(path) as fi:
  File "/home/giovanni/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gml_application_schema_toolbox/core/qgis_urlopener.py", line 59, in remote_open_from_qgis
    raise RuntimeError("Network problem when downloading {}".format(uri))
RuntimeError: Network problem when downloading #PT.INE.ADD.AUN.AC25.PT
```


I also noticed that when opening the tables is asked "Python macros are currently disabled. Do you allow this macro to run?" and selecting "yes" works, but "don't ask anymore" which I expected to be automatic "yes" does not (seems is an automatic "no" instead). Maybe this is a QGIS issue?


Also seen this, which does not seems right:

![Peek 2020-12-20 20-48](https://user-images.githubusercontent.com/1951107/102724086-d35dc480-4304-11eb-9e98-363326881d96.gif)

**Comment by Guts** [comment]
@gioman Thank you for testing again! The first step was to make the plugin properly installable on QGIS 3.16 (and 3.12, 3.14).

Could you please create a dedicated ticket for each issue with maximum details (screenshots, etc.) as you did here? It'll help us to track on them.

**Comment by gioman** [comment]
> Could you please create a dedicated ticket for each issue with maximum details (screenshots, etc.) as you did here? It'll help us to track on them.

@Guts done, but what about



> I also noticed that when opening the tables is asked "Python macros are currently disabled. Do you allow this macro to run?" and selecting "yes" works, but "don't ask anymore" which I expected to be automatic "yes" does not (seems is an automatic "no" instead). Maybe this is a QGIS issue?

this is QGIS or plugin problem?

**Comment by Guts** [comment]
I close here. I'll keep in touch about related issues.

**Comment by gioman** [comment]
ok.
